networks:
  gestrym-network:
    external: true

services:
  gestrym-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_AUTH: ${VITE_BASE_AUTH:-/gestrym-auth}
        VITE_BASE_PROGRESS: ${VITE_BASE_PROGRESS:-/gestrym-progress}
        VITE_BASE_NUTRITION: ${VITE_BASE_NUTRITION:-/gestrym-nutrition}
    image: ${FRONTEND_IMAGE:-jhonnier/front-web:${VERSION:-1.0.0}}
    container_name: gestrym-frontend
    restart: always
    env_file:
      - stack.env
    networks:
      - gestrym-network
